sudo: Required
services:
  - docker

before_install:
  - docker build -t conaryh/client -f Dockerfile.dev .

script:
  - docker run -e CI=true conaryh/client npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-production-grade-flow'
  env: 'DockerProductionGradeFlow-env'
  bucket_name: 'elasticbeanstalk-us-east-2-552368605510'
  bucket_path: 'docker-production-grade-flow'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
