version: '3'
services:
  web:
    build:
      context: . #can place foldder name
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
